# Generated by Django 5.2 on 2025-04-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='mode',
            field=models.CharField(choices=[('first_run', 'First Run Movies'), ('casual', 'Casual Viewing')], default='first_run', help_text='The mode this conversation belongs to (First Run or Casual Viewing)', max_length=10),
        ),
    ]
