# Generated by Django 5.2 on 2025-04-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_conversation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='distance_miles',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="Distance in miles from the user's location", max_digits=5, null=True),
        ),
    ]
