source 'https://rubygems.org'
ruby '3.3.6'  # Add explicit Ruby version

gem 'sinatra', '~> 4.1'
gem 'puma', '~> 6.6'
gem 'fast-mcp', '~> 1.0.0', require: 'fast_mcp'
gem 'faraday', '~> 2.12'
gem 'json', '~> 2.6'
gem 'dotenv', '~> 2.8'
gem 'dry-schema', '~> 1.13'
gem 'rackup', '~> 2.1'  # Moved from development group

group :development do
  gem 'rerun', '~> 0.14'
end

group :test do
  gem 'minitest', '~> 5.18'
  gem 'rack-test', '~> 2.1'
  gem 'webmock', '~> 3.18'
  gem 'mocha', '~> 2.0'
end
